run "cd #{config.release_path}/web"
run "exec #{config.release_path}/vendor/bin/drush -y cache-rebuild"
run "exec #{config.release_path}/vendor/bin/drush -y updatedb"
run "exec #{config.release_path}/vendor/bin/drush -y config-import"
run "exec #{config.release_path}/vendor/bin/drush -y entup"
run "exec #{config.release_path}/vendor/bin/drush -y config-set system.performance cache.page.max_age 10800"
run "exec #{config.release_path}/vendor/bin/drush -y config-set system.performance css.preprocess 1"
run "exec #{config.release_path}/vendor/bin/drush -y config-set system.performance js.preprocess 1"