run "exec cd #{config.release_path}/web"
run "exec ../vendor/bin/drush -y cache-rebuild"
run "exec ../vendor/bin/drush -y updatedb"
run "exec ../vendor/bin/drush -y config-import"
run "exec ../vendor/bin/drush -y entup"
run "exec ../vendor/bin/drush -y config-set system.performance cache.page.max_age 10800"
run "exec ../vendor/bin/drush -y config-set system.performance css.preprocess 1"
run "exec ../vendor/bin/drush -y config-set system.performance js.preprocess 1"